In [1]:
import melt_functions as ice_melt
import numpy as np
import xarray as xr
import scipy.io as sio
from plot_icebergshape import plot_icebergshape
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d, interp2d
from matplotlib import cm,colors
import pickle
import geopandas as gpd
from mpl_toolkits.axes_grid1 import make_axes_locatable
import os
import pandas as pd
import dataframe_image as dfi

dt = 50

psw = 1024 #kg m3
csw = 3974 #J kg-1 C-1
day2sec = 86400
Volume_test = 28e3 * 5e3 * 300 #km3 Helheim Fjord test

coeff_1_path = '/media/laserglaciers/upernavik/iceberg_py/outfiles/helheim/Qib/coeff_1_melt_rates/'
coeff_4_path = '/media/laserglaciers/upernavik/iceberg_py/outfiles/helheim/Qib/coeff_4_melt_rates//'

coeff_1_list = sorted([nc for nc in os.listdir(coeff_1_path) if nc.endswith('nc')])
coeff_4_list = sorted([nc for nc in os.listdir(coeff_4_path) if nc.endswith('nc')])


constant_tf_55 = 5.73 # from Slater 2022 nature geoscience
constant_tf_67 = 6.67 # from Slater 2022 nature geoscience
constant_tf_8 = 7.62 # from Slater 2022 nature geoscience

dQ_dt_HEL_55 = psw * csw * ( (Volume_test * constant_tf_55) / (dt * day2sec) )
dQ_dt_HEL_67 = psw * csw * ( (Volume_test * constant_tf_67) / (dt * day2sec) )
dQ_dt_HEL_8 = psw * csw * ( (Volume_test * constant_tf_8) / (dt * day2sec) )

os.chdir(coeff_1_path)
dQ_dt_list = [dQ_dt_HEL_55, dQ_dt_HEL_67, dQ_dt_HEL_8]

tfs = [constant_tf_55, constant_tf_67, constant_tf_8]
urels = [0.01, 0.05, 0.10] #m s-1

cols = ['coeff', 'urel', 'tf', 'dt', 'Qib', 'Qaww', 'melt_rate_avg_m3s', 'melt_rate_mday', 'percentage']
coef_1_dict = {}

series_list1 = []
for i,nc in enumerate(coeff_1_list):
    
    Qib = xr.open_dataset(nc)
    Qib_val = Qib.Qib.data
    
    percentage = Qib_val/dQ_dt_list[i]
    print(f'coeff 1: {percentage:.2f}')
    coef_1_dict['coeff'] = 1
    coef_1_dict['urel'] = urels[i]
    coef_1_dict['tf'] = tfs[i]
    coef_1_dict['dt'] = 50
    coef_1_dict['Qib'] = f'{(Qib_val/1e11):.2f}'
    coef_1_dict['Qaww'] = f'{(dQ_dt_list[i]/1e11):.2f}'
    coef_1_dict['melt_rate_avg_m3s'] = f'{Qib.melt_rate_avg.data:.2f}'
    coef_1_dict['melt_rate_mday'] = f'{Qib.melt_rate_intergrated.data:.2f}'
    
    coef_1_dict['percentage'] = f'{(Qib_val/dQ_dt_list[i])*100:.2f}'
    
    series = pd.Series(coef_1_dict)
    series_list1.append(series)

df_1 = pd.DataFrame(series_list1, columns=cols)   
os.chdir(coeff_4_path)

coef_4_dict = {}
series_list = []
for i,nc in enumerate(coeff_4_list):
    
    Qib = xr.open_dataset(nc)
    Qib_val = Qib.Qib.data
    
    percentage = Qib_val/dQ_dt_list[i]
    print(f'coeff 4: {percentage:.2f}')
    
    coef_4_dict['coeff'] = 4
    coef_4_dict['urel'] = urels[i]
    coef_4_dict['tf'] = tfs[i]
    coef_4_dict['dt'] = 50
    coef_4_dict['Qib'] = f'{(Qib_val/1e11):.2f}'
    coef_4_dict['Qaww'] = f'{(dQ_dt_list[i]/1e11):.2f}'
    coef_4_dict['melt_rate_avg_m3s'] = f'{Qib.melt_rate_avg.data:.2f}'
    coef_4_dict['melt_rate_mday'] = f'{Qib.melt_rate_intergrated.data:.2f}'

    
    coef_4_dict['percentage'] = f'{(Qib_val/dQ_dt_list[i])*100:.2f}'
    
    series = pd.Series(coef_4_dict)
    series_list.append(series)
    


df_1 = pd.DataFrame(series_list1, columns=cols)
df_4 = pd.DataFrame(series_list, columns=cols)

df_concat = pd.concat([df_1, df_4])

coeff 1: 0.02
coeff 1: 0.11
coeff 1: 0.23
coeff 4: 0.09
coeff 4: 0.46
coeff 4: 0.92

In [2]:
df_concat.reset_index(inplace=True,drop=True)
df_concat

   coeff  urel    tf  dt   Qib  Qaww melt_rate_avg melt_rate_mday percentage
0      1  0.01  5.73  50  0.05  2.27        169.42         145.13       2.22
1      1  0.05  6.67  50  0.30  2.64        254.06         350.32      11.39
2      1  0.10  7.62  50  0.70  3.01        385.92         628.87      23.24
3      4  0.01  5.73  50  0.20  2.27        216.44         258.56       8.90
4      4  0.05  6.67  50  1.20  2.64        534.06         875.78      45.50
5      4  0.10  7.62  50  2.78  3.01       1037.71        1306.43      92.34

In [3]:
# pd.options.display.latex.repr = True
l = df_concat.to_latex(
    index=False,  # To not include the DataFrame index as a column in the table
    position="htbp",  # The preferred positions where the table should be placed in the document ('here', 'top', 'bottom', 'page')
    column_format="|l|l|l|l|l|l|l|",  # The format of the columns: left-aligned with vertical lines between them
    escape=False,  # Disable escaping LaTeX special characters in the DataFrame
    float_format="{:0.2f}".format  # Formats floats to two decimal places
)

In [4]:
df_concat.reset_index(drop=True, inplace=True)

In [5]:
df_concat

   coeff  urel    tf  dt   Qib  Qaww percentage
0      1  0.01  5.73  50  0.05  2.40       2.10
1      1  0.05  6.67  50  0.30  2.80      10.74
2      1  0.10  7.62  50  0.70  3.20      21.92
3      4  0.01  5.73  50  0.20  2.40       8.39
4      4  0.05  6.67  50  1.20  2.80      42.91
5      4  0.10  7.62  50  2.78  3.20      87.08

In [6]:
dfi.export(df_concat, '/media/laserglaciers/upernavik/iceberg_py/figs/df_concat_vol_28km_length.png')

In [17]:
pd.options.display.latex.repr = True

OptionError: No such option

In [19]:
help(dfi.export)

Help on function export in module dataframe_image._pandas_accessor:

export(obj: pandas.core.frame.DataFrame, filename, fontsize=14, max_rows=None, max_cols=None, table_conversion: Literal['chrome', 'matplotlib', 'html2image', 'playwright', 'selenium'] = 'chrome', chrome_path=None, dpi=None, use_mathjax=False)
    Export a styled DataFrame as png to a file

    Parameters
    ----------
    filename : str or file-like
        The file location where the image will be saved. Provide a string
        to specify a file location on your local machine or a file-like object
        that has a `write` method.

    fontsize : int
        Font size in points

    max_rows : int
        Maximum number of rows to output from DataFrame. This number is passed
        to the `to_html` DataFrame method.

        To prevent accidentally creating images with large numbers of rows,
        an error will be raised for DataFrames with more than 100 rows.
        Set this parameter explicitly to override this error. Use -1 for all rows.

    max_cols : int
        Maximum number of rows to output from DataFrame. This number is passed
        to the `to_html` DataFrame method.

        To prevent accidentally creating images with large numbers of columns,
        an error will be raised for DataFrames with more than 30 columns.
        Set this parameter explicitly to override this error. Use -1 for all columns.

    table_conversion : 'chrome' or 'matplotlib', default 'chrome'
        DataFrames will be converted to png via Chrome or matplotlib. Use chrome
        unless you cannot get it to work. matplotlib provides a decent
        alternative.

    chrome_path : str, default `None`
        Path to your machine's chrome executable. When `None`, it is
        automatically found. Use this when chrome is not automatically found.

    dpi : int, default `None`
        Dots per inch - Use this to change the resolution ("quality") of the image.

        If `table_conversion`=`matplotlib`, this value is directly passed to
        the "savefig" method. When `None`, the figure's DPI is used.

        If `table_conversion`=`chrome`, the dpi value is converted to a
        "device scale factor" but should provide the same effect. When `None`,
        the "device scale factor" is 1.